# Generated by Django 6.0 on 2026-01-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ecomerce', '0001_initial'), ('ecomerce', '0002_productmodel_color_productmodel_description_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.FloatField()),
                ('color', models.TextField(default='No especificado')),
                ('description', models.TextField(default='Sin descripción')),
                ('dimensions', models.FloatField(default=0.0)),
                ('seller', models.TextField(default='Desconocido')),
            ],
        ),
    ]
