# Generated by Django 6.0 on 2026-01-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.TextField(default='No especificado'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='dimensions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.TextField(default='Desconocido'),
        ),
    ]
