# Generated by Django 6.0 on 2026-01-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0001_squashed_0002_add_changes_delete_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('BR', 'BORRADOR'), ('PU', 'PUBLICO'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
    ]
