# Generated by Django 6.0 on 2026-01-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0003_productmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PU', 'PUBLICADO'), ('BR', 'BORRADO'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
    ]
